"""seed upgrade

Revision ID: 1618d7313f16
Revises: f47d25cba17e
Create Date: 2024-02-19 21:59:39.761002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1618d7313f16'
down_revision = 'f47d25cba17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('sound_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sound_device', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('laptop', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('accessory', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
